[package]
name = "bevy_road-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opendrive = { path = "../opendrive" }
ordered-float = { version = "4.2.0" }
