[package]
name = "building"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13"
bevy_road-core = { path = "../bevy_road-core" }
ordered-float = "4.2.0"
